name: NASA Server CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Used Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
